version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senhaAdmin123
    volumes:
      - tattoo-db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - tattoo-network

volumes:
  tattoo-db-data:

networks:
  tattoo-network: