version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000" # 👈 Garanta o mapeamento correto
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tattoo-app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - tattoo-db:/data/db

volumes:
  tattoo-db: