version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=segredo_super_secreto
      - JWT_EXPIRES_IN=1d
    depends_on:
      - mongo

mongo:
  image: mongo:latest
  ports:
    - "27018:27017"


